### PR TITLE
Add basic slick support and make the WebCommand URI's configurable

### PR DESCRIPTION
**Pull request by crisadamo**
- I added a basic slick support by removing the hardcoded play database configuration paths and using the  database paths configured on the application configurations.

- The migrations scripts now should be placed on the following path:
  `conf/migration/<dbType>/name` where dbType is either "db" for default databases or "slick" for slicks databases

- I made the WebCommands URI paths configurable through the configurations keys:
  ```
  flyway.webCommand.baseURI = "my/admin/uri"
  flyway.webCommand.baseName = "migrations"
  ```

### CODE REVIEW

**Comment by tototoshi** [comment]
Thanks. Could you split this into two(slick p-r/webcommand p-r)  pull requests?

**Comment by crisadamo** [comment]
Sure, I'll do that and the I send you the new PRs

**Comment by schmitch** [comment]
Any updates on this?

**Comment by athieriot** [comment]
That would be really nice to have this :)

**Comment by ssanj** [comment]
I think this PR is definitely needed given that Play and Slick are so tightly coupled.

+1.

**Comment by ssanj** [comment]
@tototoshi if you are happy with the content of the PR and if @crisadamo doesn't mind/have the time, I am happy to have a go at creating two PRs from this PR.

**Comment by crisadamo** [comment]
Sorry for the wait, I was really busy. I will work on this merge on the weekend,

**Comment by ssanj** [comment]
I'm not sure if @crisadamo got around to merging these changes? In the meantime if someone needs to use Flyway with Play and Slick I've documented a workflow [here](http://sanj.ink/posts/2015-12-18-using-flyway-with-play-2_4-and-slick.html).

**Comment by tototoshi** [comment]
After some thought and consideration, Now I think this PR is not acceptable.
flyway-play should not depend on play-slick or other database libraries except JDBC.
This PR doesn't make flyway-play depend on the jars of slick, but in code level it depends.


```scala
  private def getFlyway(dbName: String, dbType: String): Option[Flyway] = {
    flyways.find {
      case (DefaultDatabaseInfo(name, fw), _) if dbType == "db" && dbName == name => true
      case (SlickDatabaseInfo(slickName, slickFw), _) if dbType == "slick" && dbName == slickName => true
      case _ => false
    }.map(_._2)
  }
```


If new play-somedblibraries appears, we have to add the case to this code? Maybe it's not the sane way. I think the best solution is to wrote something called play-flyway-slick like play-evolutions-slick. Or, simply define `db.${dbname}.*` as usual.


```
slick.dbs.yourAwesomeDbName.driver = "slick.driver.H2Driver$"
slick.dbs.yourAwesomeDbName.db.driver = "org.h2.Driver"
slick.dbs.yourAwesomeDbName.db.url="jdbc:h2:mem:example2;db_CLOSE_DELAY=-1"
slick.dbs.yourAwesomeDbName.db.username="sa"
slick.dbs.yourAwesomeDbName.db.password="secret"

// I have not tested yet but should work
db.yourAwesomeDbName = ${slick.dbs.yourAwesomeDBName.db}
```

**Pull request closed without merging**
