### PR TITLE
Update flyway version

### PR DESCRIPTION
**Pull request by nafg**

### CODE REVIEW

**Comment by nafg** [comment]
Consider using @scala-steward to automatically update dependencies. Please see https://github.com/scala-steward-org/scala-steward#quick-start-guide

**Comment by nafg** [comment]
Umm this didn't build

**Comment by tototoshi** [comment]
Thank you for the pull request.  Fixed the error. 
https://github.com/flyway/flyway-play/commit/053759ad5f0fc8316a2c448033029043581693d3

I'll release it after some more tests. (Maybe next Tuesday)

**Comment by nafg** [comment]
Thanks!

In general how actively do you maintain this?

Do you have Scala Steward set up?

**Comment by tototoshi** [comment]
I don't maintain it very actively, but I use this plugin too, so I don't think I'll abandon it for the time being.

scala-steward is a good idea. I'll try it later.

**Comment by tototoshi** [comment]
@nafg
I set up scala-steward today.
I also switched from travis ci to GitHub Actions.

**Comment by nafg** [comment]
That's great! Thanks.

**Pull request merged**
