### PR TITLE
Add support for several Flyway configuration parameters. #35

### PR DESCRIPTION
**Pull request by Dziman**
Add possibility to provide more Flyway parameters.
Remove default values: will be used default Flyway's values for parameters.

### CODE REVIEW

**Comment by mosche** [comment]
@tototoshi Any chance to merge this? This would be great to have!
Any way we can assist?

**Comment by 0xbaadf00d** [comment]
@tototoshi Hope this PR will be soon merged

**Comment by tototoshi** [comment]
Thanks.

**Comment by tototoshi** [comment]
Sorry I reverted this PR because of some problems. But I want to merge this again. Could you make some fix?

- Don't want to use `Option[T]` fields for Configuration. Please set default value if it is possible.
- coding style (I don't like infix style `obj foreach func`. Please change it to `obj.foreach(func)`)

**Comment by tototoshi** [comment]
or could you split this p-r into two? 

- Add possibility to provide more Flyway parameters.
- Remove default values: will be used default Flyway's values for parameters.

I'm also interested in removing default values itself.

**Pull request merged**
