### PR TITLE
New configuration parameter - dbFolder

### PR DESCRIPTION
**Pull request by gomes-rocket**
This new parameter - dbFolder, will allow users to define a different folder name rather than default, which is the dbName. This allow us to instead of having this configuration:

db.migration_other.driver=....
db.migration_other.user=....
db.migration_other.migration.table="schema_version"

with this file structure

---- conf
-------- db
------------ migration
------------------- migration_other
-------------------------------- V1___create.sql

We can have something like:

db.migration_other.driver=....
db.migration_other.user=....
db.migration_other.migration.table="schema_version"
**db.migration_other.migration.dbFolder="customFolder"**

with this file structure

---- conf
-------- db
------------ migration
------------------- customFolder
-------------------------------- V1___create.sql

### CODE REVIEW

**Comment by schonbachler** [comment]
I have the same requirement. I hope that this request is integrated soon.

**Comment by tototoshi** [comment]
Thank you for suggestion. I want to merge, but I want to change only the setting name. How about making it "scriptsDirectory" instead of "dbFolder"?

**Comment by gomes-rocket** [comment]
> Thank you for suggestion. I want to merge, but I want to change only the setting name. How about making it "scriptsDirectory" instead of "dbFolder"?

Works for me! Could you change it then? Thanks

**Comment by tototoshi** [comment]
Thanks!

**Pull request merged**
